### ISSUE TITLE
Request for cooperation: bash-modules

### ISSUE THREAD

**Issue by vlisivka** [LamdaLamdaLamda/bash-collection#1]
I'm author of [bash-modules](https://github.com/vlisivka/bash-modules) project, which is released under LGPLv2+ license.

Bash-modules is a collection of useful bash functions for development with unofficial strict mode turned on.

I'm preparing to release version 4.0 of bash-modules, so I'm looking for feedback.

**Comment by LamdaLamdaLamda** [comment]
I appreciate you request for cooperation. What kind of feedback do you request? How can I eventually support your project?

**Comment by vlisivka** [comment]
I have two major problems:

* as non-native speaker, I struggle with English sometimes, so I'm keeping documentation short.
* it's hard for me to make decisions as solo developer. For example, 
  - I chose to use "#>" as prefix for documentation comments, because it's easy to parse, but I want to hear someone else opinion. E.g., maybe it better to copy someone else documentation comments style.
  - which markup language we should use in built-in documentation? Markdown (github), asciidoctor, html, etc.?
  - do we need to have support for versions? E.g. `. import.sh log-3.0` .
  - do we need to have a package manager, e.g. `bapt install fancy-prompt` .
  - do we need to support parameters for modules. e.g. ". import.sh log(simple,color_scheme=dark)"? If so, how? E.g. maybe each module must have a `main()` function, which will be called with arguments.

Also, project needs:
* more functions. I include functions only which are used in my own scripts (because it's started this way years ago, and because it's allow me to test them in real world conditions).
* more documentation and automatic generation of a static site with documentation from sources.
* more examples and real scripts.
* tutorial: how to convert quick-and-dirty bash script into proper utility with arguments, options, and built-in documentation.
* a way to convert built-in documentation into man pages, markdown pages, html, pdf. (Via pandoc?).

**Comment by vlisivka** [comment]
I copied my reply here: https://github.com/vlisivka/bash-modules/discussions/17 .

**Comment by LamdaLamdaLamda** [comment]
I am going to close this issue.I will open issues for the feedback, you requested.
